# ACM Research Week 2: Linear Regression

## Background
### Dot Product
Assume we have two vectors $\vec{v} = (v_1, v_2, ..., v_n)$ and $\vec{w} = (w_1, w_2, ..., w_n)$.

The *dot product* is defined as the sum of the product of corresponding components:

$$\vec{v}\cdot\vec{w} = v_1 w_1 + v_2 w_2 + ... + v_n w_n$$

In [ ]:
import numpy as np
v = np.array([1, 2])
w = np.array([3, 4])
# Dot product here!

11

### Matrix Multiplication
Let's say have two matrices $A$ and $B$ as defined below:

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix},\:\:
B = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}
$$

The *product* $AB$ of two matrices is defined as the dot product between the rows of $A$ with the columns of $B$:

$$AB = \begin{bmatrix}
1(7) + 2(9) + 3(11) & 1(8) + 2(10) + 3(12) \\
4(7) + 5(9) + 6(11) & 4(8) + 5(10) + 6(12)
\end{bmatrix} = \begin{bmatrix}58 & 64 \\ 139 & 154\end{bmatrix}$$

Note than if $A$ is of $a \times b$ and $B$ is of $b \times c$, then $AB$ is of size $a \times c$. 

The product also doesn't exist if the number of rows in A doesn't match the number of columns in C.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Multiply matrices here!

array([[ 58,  64],
       [139, 154]])

### Transpose a Matrix
Rows <-> columns. That's it.

In [ ]:
# Transpose here!

array([[1, 4],
       [2, 5],
       [3, 6]])

## Main Content

### Intro

**Linear regression** is one of the most basic machine learning tasks: fit a linear model to some data.

You might have seen a line in 2D as $y=mx+b$, where $m$ is the slope and $b$ is the y-intercept.

Let's first *vectorize*, this, i.e. think of it within the realm of matrix multiplication. Instead of writing our line as $y=mx+b$, we can rewrite the right side of that equation as $y = w^{\top}x$, where $x_0 = 1$ and $w$ is a $1\times 2$ vector.

As an example, how would we write the equation $y=3x+4$ in this form?
Well, $w = \begin{bmatrix} 4 \\ 3 \end{bmatrix}$, and $x = \begin{bmatrix} 1 \\ x_1 \end{bmatrix}$, where $x_1$ takes the place of $x$ in the slope-intercept form equation. We can verify this is the same by multiplying it out:

$$
\begin{align}
y &= w^{\top} x \\
y &= \begin{bmatrix} 4 & 3 \end{bmatrix} \begin{bmatrix} 1 \\ x_1 \end{bmatrix} \\
y &= 4 + 3x_1 \;\checkmark
\end{align}
$$

In [ ]:
def equation(x1):
  # Equation here!
print(equation(1))
print(equation(4))

[[7]]
[[16]]


### Multivariate Linear Equations: Vectorized
Now, let's extend this concept to multiple dimensions and multiple points.
Let's say we had the equation $y = w_0x_0 +w_1 x_1 + w_2 x_2 + ... + w_n x_n$. This is a line in $n$ dimensions—for us, we'll say this model takes $n$ *features*. How would we vectorize this, and use it for multiple points?

Let's say we have the **design matrix**:
$$
X = \begin{bmatrix}
1 & 0.315 & 0.083 & 0.849 \\
1 & 0.522 & 0.079 & 0.530 \\
1 & 0.558 & 0.252 & 0.958 \\
1 & 0.134 & 0.241 & 0.473
\end{bmatrix}
$$

Here, we have 3 *features* and 4 *data points*/*training examples*. We can also say $n=3$ and $m=4$.

Let's say we also have a vector of *weights*:

$$ w = 
\begin{bmatrix}
w_0 \\
w_1 \\
w_2 \\
w_3
\end{bmatrix}
=
\begin{bmatrix}
0.012 \\
0.951 \\
0.301 \\
0.868
\end{bmatrix}$$

Therefore, the vectorized version of the multivariate linear equation above would be:

$$ y = Xw $$

In [ ]:
X = np.array([
     [1, 0.315, 0.083, 0.849],
     [1, 0.522, 0.079, 0.530],
     [1, 0.558, 0.252, 0.958],
     [1, 0.134, 0.241, 0.473]
])
w = np.array([[0.012], [0.951], [0.301], [0.868]])
# y = X times w!

### The Problem of Linear Regression
With this knowledge, we can now talk about multivariate linear regression.

> **The task $T$**: With equation $\hat{y} = Xw$, have $\hat{y} \approx y$ for any $X$ by finding the optimal $w$.

> **The experience $E$**: $X_{train}$, as provided

> **Performance measure $P$**: (Euclidean) distance from $\hat{y}$ to $y$

Let's define all of these in terms of matrices and matrix equations:

- The task $T$: $\hat{y} = Xw$, $w \in \mathbb{R}^n$
- The experience $E$: design matrix of data points
- The performance measure $P$: $J(w) = ||\hat{y}- y||^2$


In [ ]:
y_hat = np.array([[1.1283],
       [1.0000],
       [1.43],
       [0.6234]])
# print performance measure!
y_hat = np.array([[1.07348 ],
       [0.992241],
       [1.450054],
       [0.622539]])
# print performance measure!

0.003032619598487279
5.082120056479053e-32


### Gradient Descent
How do we use $P$ to get better at $T$?

The answer is **gradient descent**. The basic idea behind gradient descent is to use the *partial derivative* of a function to iteratively converge to a (ideally global) minimum.

The since this is vectorized, we need to find the partial derivative with respect to every parameter in $w$. In linear algebra, this is also called the gradient $\nabla$. The gradient of the MSE function is $$\nabla J(w) = \frac{1}{m} X^{\top}(Xw - y)$$

So how do we update the weights $w$ given the gradient? Well, we multiply the gradient by a small decimal $\alpha$ (called the *learning rate*), which is usually set to something small like `0.001` and subtract it from the existing weights.

> **Note**: The learning rate will be different for every dataset and ML algorithm. Set it too small, and your model will take forever to *converge* (reach the minimum). Set it too high, and it may overshoot the minimum and fail to converge.

As a matrix equation, it looks something like this:

$$w = w - \frac{\alpha}{m}X^{\top}(Xw - y)$$

In [ ]:
X = np.array([
     [1, 0.315, 0.083, 0.849],
     [1, 0.522, 0.079, 0.530],
     [1, 0.558, 0.252, 0.958],
     [1, 0.134, 0.241, 0.473]
])
w = np.array([[0.012], [0.951], [0.301], [0.868]])
y_hat = np.dot(X, w)
y = np.array([[1.5],
       [0.23],
       [1.0],
       [0.6]])
alpha = 0.001
m = 4
# iteratively do gradient descent!

[[0.01179792]
 [0.95087058]
 [0.30096408]
 [0.86787908]]
[[0.01159619]
 [0.95074129]
 [0.30092823]
 [0.86775841]]
[[0.01139479]
 [0.95061214]
 [0.30089242]
 [0.86763798]]
[[0.01119374]
 [0.95048313]
 [0.30085668]
 [0.8675178 ]]
[[0.01099303]
 [0.95035426]
 [0.30082098]
 [0.86739787]]
[[0.01079265]
 [0.95022552]
 [0.30078535]
 [0.86727818]]
[[0.01059262]
 [0.95009691]
 [0.30074977]
 [0.86715874]]
[[0.01039293]
 [0.94996844]
 [0.30071425]
 [0.86703955]]
[[0.01019357]
 [0.9498401 ]
 [0.30067878]
 [0.8669206 ]]
[[0.00999455]
 [0.9497119 ]
 [0.30064336]
 [0.86680189]]


## Practice: Implementing a Linear Regression Model
Steps to most ML projects:
1. Pull in data
2. Initialize weights
3. Run gradient descent iteratively
4. Test on new data
5. Report results

[Dataset!](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1: Pull in Data

## Step 2: Initialize Weights

# Step 3: Run Gradient Descent

## Step 4: Test on New Data

## Step 5: Report Results